apiVersion: v1
kind: Namespace 
metadata:
  name: ccpp-docs
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ccpp-docs
  namespace: ccpp-docs
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ccpp-docs
  template:
    metadata:
      labels:
        app: ccpp-docs
    spec:
      containers:
      - name: ccpp-docs
        image: ncote/mkdocs_test
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8000
          hostPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: docs-svc
  namespace: ccpp-docs
spec:
  ports:
  - port: 8000
    name: default
  selector:
    app: ccpp-docs
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-docs
  namespace: ccpp-docs
  labels:
    app: ccpp-docs
spec:
  ingressClassName: nginx
  rules:
  - host: docs.test.dev
    http:
      paths:
      - path: /foo
        pathType: Prefix
        backend:
          service:
            name: docs-svc
            port:
              number: 8000
        
