site_name: CCPP Documentation
site_url: https://jira.ucar.edu/secure/RapidBoard.jspa?rapidView=220&projectKey=CCPP
site_description: Documentation for the CISL Cloud Pilot Program
repo_url: https://github.com/NCAR/cisl-cloud/tree/main/docs
nav:
  - Home: index.md
  - About: overview/about.md
  - Use Cases: overview/use-cases.md
  - Availability:
    - Current Offering: overview/availability.md
    - Hardware: overview/hw-resources.md
    - Potential Features: overview/features.md
    - Potential Services: overview/services.md
  - Contact Us: overview/contact.md
  - How-Tos: 
      - Agile Interaction: how-to/agile.md
      - Documentation Site Build: how-to/build-docs.md
      - Kubernetes (k8s) JupyterHub:
        - Install JupyterHub on k8s: how-to/k8sJH/install.md
        - Customize Jupyter Docker Image: how-to/k8sJH/customize-docker.md
        - Setup GitHub Action to Build and Push Docker Image: how-to/k8sJH/setup-gh-act.md
  - SLA's:
      - GLADE: slas/glade.md
theme: 
  name: readthedocs
  logo: 'images/ncar-cisl-white.png'
extra_css:
  - "css/extra.css"
extra_javascript:
  - js/popper.min.js
  - js/tippy-bundle.umd.js
  - js/clipboard.js
  - js/extra.js