# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: CISL Cloud Pilot
author: The CISL Cloud Pilot Team
logo: images/ncar-cisl-blue.png
email: "cisl-cloud-pilot@ucar.edu"

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: auto
  exclude_patterns:
    - '*how-to/K8s/tf-namespace*'

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/NicholasCote/CCPPdocs # Online location of your book
  path_to_book: jupyter-docs  # Optional path to your book, relative to the repository root
  branch: master  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
#######################################################################################
# HTML-specific settings
html:
  announcement: "This project in currently in the Pilot phase"
  favicon: images/favicon.ico
  home_page_in_navbar: false
  use_issues_button: true
  use_repository_button: true
  extra_navbar              : Visit our <a href="https://github.com/NCAR/cisl-cloud">GitHub Repository</a>
    <div>This book is powered by <a href="https://jupyterbook.org">Jupyter Book</a></div>

#######################################################################################
# Launch button settings
launch_buttons:
  notebook_interface        : classic  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url             : "https://mybinder.org"  # The URL of the BinderHub (e.g., https://mybinder.org)
  jupyterhub_url            : "https://jupyter.k8s.ucar.edu/"  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)

sphinx:
  config: