# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: CISL Cloud Pilot
author: The CISL Cloud Pilot Team
logo: images/CISL-contemp-logo-blue.png
email: "cisl-cloud-pilot@ucar.edu"

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: auto
  exclude_patterns:
    - '*how-to/K8s/tf-namespace*'
    - '*how-to/jupyter-book/create-jb*'

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

#######################################################################################
# Launch button settings

sphinx:
  config:
    html_favicon: images/favicon.ico
    html_last_updated_fmt: '%-d %B %Y'
    html_theme: sphinx_pythia_theme
    html_theme_options:
      home_page_in_toc: false
      repository_url: https://github.com/NicholasCote/CCPPdocs # Online location of your book
      repository_branch: master
      navbar_align: content
      use_issues_button: false
      use_repository_button: false
      launch_buttons:
        notebook_interface: jupyterlab  # The interface interactive links will activate ["classic", "jupyterlab"]
        #binderhub_url: "https://mybinder.org"  # The URL of the BinderHub (e.g., https://mybinder.org)
        #jupyterhub_url: "https://jupyter.k8s.ucar.edu/"  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)
      extra_navbar: |
        <p style="font-weight: 700;">The site has moved <a href="https://ncar.github.io/cisl-cloud/">here</a>.</p><hr>
        <div>Powered by <a href="https://jupyterbook.org">Jupyter Book</a></div><br>
        Theme by <a href="https://projectpythia.org/">Project Pythia</a>
      navbar_links:
        - name: Cloud Docs
          url: "https://ncar.github.io/cisl-cloud/"